services:

    jits.services.email:
        class: JulienIts\Bundle\EmailsQueueBundle\Services\EmailService
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            router: "@router"
            twig: "@twig"
            tokenStorage: "@security.token_storage"
    
    jits.services.emails_queue:
        class: JulienIts\Bundle\EmailsQueueBundle\Services\EmailsQueueService
        arguments: 
            entityManager: "@doctrine.orm.entity_manager"
            mailer: "@mailer"
            appMode: %app.mode%