<?php

namespace JulienIts\Bundle\EmailsQueueBundle\Repository;

/**
 * EmailContextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailContextRepository extends \Doctrine\ORM\EntityRepository
{
}
